### ISSUE TITLE
Review lecture 0 part b.

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#10]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

Find links to the video and slides, at  [harris-coding-lab.github.io](harris-coding-lab.github.io )

# Update Rmd, pdf and R file in pull request

Please check the box as you go!

- [x] Watch the video with slides open. Make sure the order is roughly the same. 
    - [x] If essential code is missing from slides, please add a slide. (I don't think this should be the case.)
    - [x] Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

- [x] create a `.R` file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder)

# Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.

**Comment by michaelcgorman** [comment]
One small tweak I'd make is just to add a little explanation at 8:20 about the common shortcomings of the built-in help documentation. Namely, that it isn't always written with a new coder in mind. For example:

> Remember, if you're still struggling to understand the arguments to a function after reading this documentation, you're probably not the first person to need more information. Searching Google (for instance, by searching [sum in r]) can pull up some really helpful advice from other people's experiences.

As far as weird editing: I'm sure most people don't care about this, but I could definitely tell that pieces of audio were recorded at different times and/or in different locations. It was all mostly around the same volume, so probably not an issue. Just something I noticed to be aware of.
