### ISSUE TITLE
Review lecture 1a  (reading data files)

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#11]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

Find links to the video and slides, at  [harris-coding-lab.github.io](harris-coding-lab.github.io )

# Update Rmd, pdf and R file in pull request

Please check the box as you go!

- [x] Watch the video with slides open. Make sure the order is roughly the same. 
    - [x] If essential code is missing from slides, please add a slide. (I don't think this should be the case.)
    - [x] Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

- [x] create a `.R` file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder)

# Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.

**Comment by ryanmwebb** [comment]
In knitting the slides, I have instances of code and output running off the side of the page.  I am struggling to fix that.  

However, everything looks good otherwise.  Slides were in the correct order and content aligns well with the videos.

**Comment by anisfeld** [comment]
It's okay for output to run off esp. if it's a data frame or something
where being able to read the actual output doesn't matter that much.

Yalun will share the secret sauce in slack.  His method is some code that
shrinks all the font sizes. If your code can be broken into two lines
that'll work as well.

Thanks!
