### ISSUE TITLE
Review lesson 2b (dplyr)

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#12]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

Find links to the video and slides, at  [harris-coding-lab.github.io](harris-coding-lab.github.io )

# Update Rmd, pdf and R file in pull request

Please check the box as you go!

- [x] Watch the video with slides open. Make sure the order is roughly the same. 
    - [x] If essential code is missing from slides, please add a slide. (I don't think this should be the case.)
    - [x] Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

- [x] create a `.R` file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder)

# Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.

**Comment by jmerodriguez** [comment]
I think is fine. 
The only thing I would change is that you are assuming that they know why we put "Houston", "Dallas" and "Austin" in quotes. You teach this in the next lecture, so probably they will have that question.

**Comment by jmerodriguez** [comment]
Please let me know if it is Ok or if I should make more changes
thanks!

**Comment by anisfeld** [comment]
Thanks! Let's see how the handle not knowing about quotes. Maybe I can add something to the lab work that explains it.

**Comment by anisfeld** [comment]
@jmerodriguez I don't see the result of "create a .R file with the code used in the slides."

**Comment by jmerodriguez** [comment]
Hi, 
Sorry somehow my github desktop didn't uploaded it, even though I could see it on my files while on Master branch.

I just uploaded it directly.
sorry about that!
