### ISSUE TITLE
Review lesson 2 (vectors and data types).

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#13]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

Find links to the video and slides, at  [harris-coding-lab.github.io](harris-coding-lab.github.io )

# Update Rmd, pdf and R file in pull request

Please check the box as you go!

- [x] Watch the video with slides open. Make sure the order is roughly the same. 
    - [x] If essential code is missing from slides, please add a slide. (I don't think this should be the case.)
    - [x] Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

- [x] create a `.R` file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder)

# Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.

**Comment by sun-jia-yi** [comment]
@anisfeld :

The video and the content of the slides look good to me, although the order of the slides seemed to be slightly off in two places (as listed below) and I have made adjustments to the order according to the video:
- page 10 - 14: I put the two slides on _Warning: vector recycling_ before the two slides on _Binary operators are vectorized_, as that seemed to be the order in the video.
- page 25 - 28: I put the second slide on type coercion (about how to address the problem) after the two slides on NA, as that seemed to be the order in the video.
- also, I think slides after page 30 were not covered in the video? 

Other than these, I think the concepts/delivery all look good to me and I don't see any problems! I have put all my modifications in issue_13_review_lesson_2 branch [here](https://github.com/harris-coding-lab/harris-coding-lab.github.io/tree/issue_13_review_lesson_2).

Don't hesitate to let me know if you have any questions regarding this.

**Comment by anisfeld** [comment]
Great, thanks! I made a pull request for you.
