### ISSUE TITLE
Review lesson 3: if else statements

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#14]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

Find links to the video and slides, at  [harris-coding-lab.github.io](harris-coding-lab.github.io )

# Update Rmd, pdf and R file in pull request

Please check the box as you go!

- [x] Watch the video with slides open. Make sure the order is roughly the same. 
    - [x] If essential code is missing from slides, please add a slide. (I don't think this should be the case.)
    - [x] Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

- [x] create a `.R` file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder)

# Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.

**Comment by leandrogrespan** [comment]
1) function read_csv requires tidyverse (no mention in the slides)
2) read_csv will not work depending on the user's working directory
2) Black Jack game requires an initialized variable "score" not on slides

**Comment by anisfeld** [comment]
Hi

**Comment by anisfeld** [comment]
Hi @leandrogrespan ,

Thanks! It looks like you added these in the R script, which looks great. Do you think students are going to see the black jack game on the slides and be confused about what score is? Can you add `score <- 0` to the slide with blackjack? It might over run the slide, which brings me to my next point. 

I noticed some of the slides we have code running off the right-side of slide, and in once case text is running off the slide completely.  (see slides a/b case_when and a slide on vectorized ifelse.) Can you fix these?  Yalun has a nice way to deal with that, which I asked him to share with you.

Let me know if you have any questions!

**Comment by ryanmwebb** [comment]
I have also been struggling with fixing code that runs off the side (new to Tex), could that solution be shared with the group?

**Comment by anisfeld** [comment]
@leandrogrespan  Can you update me on this ticket.

**Comment by leandrogrespan** [comment]
I just fixed the slides according to previous recommendations (both yours and Yalun's).
