### ISSUE TITLE
Review lesson 4: grouped dplyr

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#15]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

Find links to the video and slides, at  [harris-coding-lab.github.io](harris-coding-lab.github.io )

# Update Rmd, pdf and R file in pull request

Please check the box as you go!

- [x] Watch the video with slides open. Make sure the order is roughly the same. 
    - [x] If essential code is missing from slides, please add a slide. (I don't think this should be the case.)
    - [x] Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

- [x] create a `.R` file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder)

# Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.

**Comment by yalunsu** [comment]
@anisfeld The video and slide look good to me. Below are two minor comments.

+ For the introduction of `count()` and `add_count()`, it might be helpful to start with a question (e.g. what to do if we want to know how many observations within a group), show two options with things that they already learned (i.e. `summarize` and `mutate`), and then show two shortcuts using `count()` and `add_count()`. 

+ Also, for the demo of `count()` and `add_count()`, it might be helpful to use the same number of columns. It's probably too much work for this minor issue. The only place that I was confused for a second is when you explain the idea of `mutate()` and `add_count()` via adding an additional column (starting in 11:58 of the video), the dimensions of tibble outputs also go up from `5x2` to `5x3` from the previous example using `count()`. But then I realized that you were referring to the actual process behind `summarize()` and `mutate()`. 
```
texas_housing_data %>%
    count(city, year) %>%
    head(5)

texas_housing_data %>%
    select(city, year, sales) %>%
    add_count(city, year) %>%
    head(5)
```

vs

```
texas_housing_data %>%
    count(city, year) %>%
    head(5)

texas_housing_data %>%
    select(city, year) %>%
    add_count(city, year) %>%
    head(5)
```

**Comment by yalunsu** [comment]
- I changed the font size of outputs for a few slides.
- I added a global suppression to the new warning message regarding "`summarise()` and grouping" in `dplyr` >= 1.0. It's a new experimental feature. Please see [Hadley's blog](https://www.tidyverse.org/blog/2020/05/dplyr-1-0-0-last-minute-additions/)  for more discussion.
```
options(dplyr.summarise.inform = FALSE)
```

**Comment by anisfeld** [comment]
Great! Thank you Yalun. Please remove the non-code from the .R file. Otherwise we're good to go. 

Re. count() and add_count() that's a good point. I think it's not worth changing the video, but I'll test for understanding during Q and A.
