### ISSUE TITLE
Review lab 0 material and final project

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#20]
Go through the lab material as if you were a student. 
   - [x] Suggest edits for clarity
   - [x] Add **challenge** to the beginning of the problems if they seem particularly difficult.

Go through final project
   - [x] Suggest edits for clarity

**Comment by anisfeld** [comment]
closed by #24

**Comment by michaelcgorman** [comment]
`us_deaths_by_race` plot code is cut off in the PDF. Reopening. I'll also claim the issue and make a PR to fix it.

**Comment by anisfeld** [comment]
I also realized the numbering is off and was going to fix that. Can you take a stab at that too?

**Comment by michaelcgorman** [comment]
Will do.

**Comment by michaelcgorman** [comment]
TBH I'm not sure how this'll look on the PDF once both are merged. I've never managed a PDF with git before and don't have a super good understanding of the file structure. I can check once the PRs are merged into master.

**Comment by anisfeld** [comment]
The merging of pdfs just overwrites the old pdf. I assume you've knit.

**Comment by michaelcgorman** [comment]
Yeah, I knit each version in its own branch. Should've just reused the branch, in retrospect. I'll manually copy over my changes from the first branch into the second so you can disregard the first.

**Comment by anisfeld** [comment]
Thanks! Resolved by #29
