### ISSUE TITLE
Review Lab Material 3

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#36]
Go through the lab material as if you were a student ... this means you are basically making solutions and should probably sign up for that issue as well.

Deadline: Tuesday, 5pm.

- [ ] Suggest edits for clarity
- [ ] Add challenge to the beginning of the problems if they seem particularly difficult.
- [ ] Make a pull request.

Please reach out to me with any questions about any of this.

**Comment by anisfeld** [comment]
@nluong0  it's too late for the editing part. I want to double check you're making the solutions.

**Comment by nluong0** [comment]
@anisfeld I'm so sorry, I somehow missed this issue in my inbox. I created the solutions a few days ago. Yalun has already reviewed them, and he will post them at the correct time at the beginning of this week as well.
