### ISSUE TITLE
Review lab 4 materials

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#40]
Go through the lab material as if you were a student ... this means you are basically making solutions (so I signed you up for that role).

Deadline: Friday, 5pm.

- [x] Suggest edits for clarity
- [x] Add challenge to the beginning of the problems if they seem particularly difficult.
- [x] Make a pull request.

Please reach out to me with any questions about any of this.

**Comment by anisfeld** [comment]
Hi @leandrogrespan, this was due yesterday. I'm more concerned about you making solutions. Can you verify that you're working on the solutions?

**Comment by leandrogrespan** [comment]
Hi Ari, I'll send a first version for review tonight. Working on it right now!

**Comment by leandrogrespan** [comment]
Done
