### ISSUE TITLE
Review Lesson: Iteration and loops

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#47]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

**Please check the box as you go!**

You will find the slides and video available on the course website: https://harris-coding-lab.github.io/

Watch the video with slides open. Make sure the order is roughly the same. 

- [x] If essential code is missing from slides, please add a slide. I know we don't have the following code in a slide, please add it with an appropriate title before the other method for looping over file names.

```
file_names <- list.files(pattern = "*.csv$")

output <- vector("list", length(file_names))

for (i in seq_along(file_names)) {
  output[[i]] <- read_csv(file_names[[i]]) %>%
                    mutate(year = str_extract(file_names[[i]], "[0-9]{4}"))
}

data <- bind_rows(output)
View(data)

```

- [x]  Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

 - [x] create a .R file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder). I have  

Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.
- [x] Provide any ideas you have for lab to help illuminate the material.

**Comment by alysha-21** [comment]
- may be helpful to briefly explain rep() function at 6:30
- some pauses/repeats around 10min, not a big deal but noticeable

**Comment by anisfeld** [comment]
Thanks Alysha. I think I'll fix the video after the quarter is over!
