### ISSUE TITLE
Text tweak: "Coding is requires"

### ISSUE THREAD

**Issue by michaelcgorman** [harris-coding-lab/harris-coding-lab.github.io#9]
Can't create a new branch yet, but noting for followup: slide deck [00_introduction, line 97](https://github.com/harris-coding-lab/harris-coding-lab.github.io/blob/b2ff4589b3e5b014ecbe051e5191f4703e0fdb95/slides/00_introduction.Rmd#L97) currently reads:

> Coding is requires a different modality of thinking

It should be changed to read:

> Coding requires a different modality of thinking

Happy to branch/PR once I have permission. (Or do you want us to fork/branch/PR instead?)

**Comment by anisfeld** [comment]
I prefer branch/PR.
